### ISSUE TITLE
No link provided to compile and flash

### ISSUE THREAD

**Issue by Lotrax** [citizendialogkitproject/citizen-dialog-kit#1]
See this section of the documentation.

https://github.com/citizendialogkitproject/citizen-dialog-kit#flash-the-software-on-the-electron

No link is provided. Or does this simply reference the firmware files that are on github?

**Comment by Lotrax** [comment]
Reading the booklet, it is clear this is indeed the firmware provided in the github.

http://rxd.architectuur.kuleuven.be/dataonsite/downloads/CitizenDialogKit-Booklet-v0.2.pdf

**Comment by JorgosCoenen** [comment]
Hi @Lotrax 
Thanks for checking out the project! Any particular plans? 
Let me know if there's anything else!

**Comment by Lotrax** [comment]
Hi @JorgosCoenen 
I am planning to build at least one! I've read the material, but it's unclear what kind of solar charging power bank you used, it would be great if you could point me to the exact model. Also, does the plexi let through enough light to active the cells in order to charge?

In previous projects I've used powerbanks quite often and if the load is too low the powerbanks shut down. With an e-ink screen I can imagine there isn't a continuous load.

I am also to implement this unit outdoors, so I'll have to figure out how to deal with current weather in the Netherlands. I don't think the temperatures would cause problems, but of course the casing has to be weather proof and I am wondering of cloudy weather and minimal sun hours could still charge the unit.

**Comment by JorgosCoenen** [comment]
Great to hear! Just as a personal project? Do you also plan to use the back-end? 

Yes, the power banks normally shut down. We ended up disassembling them and connecting the batteries straight to the Particle board (basically like the battery that comes with it, only larger). We have not reintegrated solar power cells at this point. 

We are now experimenting with 3D printed enclosures for better weather proofing. The plexiglass design will probably need glue and rubber to be more water resistant...

**Comment by Lotrax** [comment]
Hi Jorgos, I have just sent you an email to discuss this further.
